name: hls4ml-tutorial
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyterhub
  - pydot
  - graphviz
  - pip
  - pip:
    - jupyter==1.0.0
    - tensorflow==2.4.0
    - tensorflow_datasets==4.5.2
    - hls4ml[profiling]==0.6.0
    - qkeras==0.9.0
    - scikit-learn==1.0.2
    - conifer==0.2b0
